name: Build and Deploy to Somee

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: url-shorten-production

    steps:
    # 1. Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Adjust to match your .NET version (e.g., 8.0, 9.0)

    # 3. Publish the application to a local folder
    - name: Publish App
      run: dotnet publish -c Release -o ./publish
      
    # 3.5 Use Variable Substitution to edit the appsettings.json directly, instead of setting env variable for OS
    # Somee only receives files, so it does not know the env variables in YAML of GitHub Actions.
    # use microsoft/variable-substitution to edit file appsettings.json before uploading through FTP
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './publish/appsettings.json'
      env:
        ConnectionStrings.Default: ${{ secrets.DB_CONNECTION_STRING }}
        MessageBus.Host: ${{ secrets.MESSAGEBUS_HOST }}
        MessageBus.UserName: ${{ secrets.MESSAGEBUS_USERNAME }}
        MessageBus.Password: ${{ secrets.MESSAGEBUS_PASSWORD }}

    # 4. Sync files to Somee via FTP
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish/
        server-dir: ${{ secrets.SOMEE_ROOT_PATH }} # Replace with your actual web root directory on Somee
        protocol: ftp
        port: 21
